# Site settings
title: Ben's Blog
header-img: /img/home-bg.jpg

description: "Freelance web developer, lover of JS and all new stuff #reactjs, #redux, #docker #machinelearning... Co-founder and prev. CTO @pageyourself, involved in @AllOverSequins, @recursecenter alumni"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.benoitvallon.com" # the base hostname & protocol for your site

author: Benoit VALLON
twitter_username: benoitvallon
github_username: benoitvallon
facebook_username:
linkedin_username: benoitvallon

#http://www.gravatar.com/avatar/91d41aa67a503e6aee0e485e8e1e6490.png
gravatar: https://avatars3.githubusercontent.com/u/2761144

disqus: benoitvallon
google_analytics: UA-63129957-1
google:
  #code goes here (the DSN TXT record does not work here, breaks the redirection to github pages)
  webmaster-tools: 702z24ksUQH2oG6USnrPutOqAgBgNmvqe8hI9_qgvPk

# Build settings
markdown: redcarpet # kramdown/redcarpet

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

permalink: /:categories/:title/
paginate: 10

# exclude directories and/or files from the conversion
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:
  - jekyll-sitemap
