# Site settings
title: Benoit VALLON
header-img: img/home-bg.jpg
email: benoitvallon@gmail.com
description: "Freelance web developer, lover of JS and all new stuff #flux #reactjs #docker... Co-founder and prev. CTO @pageyourself, involved in @AllOverSequins"
baseurl: ""
url: "http://blog.benoitvallon.com"
author: Benoit VALLON
twitter_username: benoitvallon
github_username: benoitvallon
facebook_username:
linkedin_username: benoitvallon

#http://www.gravatar.com/avatar/91d41aa67a503e6aee0e485e8e1e6490.png
gravatar: https://avatars3.githubusercontent.com/u/2761144

disqus: benoitvallon
google_analytics: UA-63129957-1
google:
  webmaster-tools: #code goes here

# Build settings
markdown: redcarpet # kramdown/redcarpet

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
