# Site settings
title: Benoit VALLON
header-img: img/home-bg.jpg
email: benoitvallon@gmail.com
description: "Freelance web developer, lover of JS and all new stuff #flux #reactjs #docker... Co-founder and prev. CTO @pageyourself, involved in @AllOverSequins"
baseurl: ""
url: "http://benoitvallon.github.io"
twitter_username: benoitvallon
github_username:  benoitvallon
facebook_username:  benoitvallon

# Build settings
markdown: redcarpet # kramdown/redcarpet

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
